spring:
  application:
    name: nacos-consul-adapter

management:
  server:
    port: 8080 # 找运维分配端口, 这个端口和提供 web 服务的端口隔离，ECS 安全组策略不允许外网访问
  # health 显示详情
  endpoint.health.show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'loggers', 'prometheus']

logging:
  level:
    io:
      github:
        chengliu:
          nacosconsuladapter: debug