spring:
  application:
    name: nacos-consul-adapter
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.104:8848

logging:
  level:
    io:
      github:
        chengliu:
          nacosconsuladapter: info