spring:
  application:
    name: nacos-consul-adapter
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.80:8848,192.168.3.86:8848,192.168.3.88:8848

logging:
  level:
    io:
      github:
        chengliu:
          nacosconsuladapter: info