server:
  port: 8090

management:
  server:
    port: 9090 # 找运维分配端口, 这个端口和提供 web 服务的端口隔离，ECS 安全组策略不允许外网访问
  # health 显示详情
  endpoint.health.show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'loggers', 'prometheus' ]

spring:
  application:
    name: nacos-consul-adapter

logging:
  level:
    io:
      github:
        chengliu:
          nacosconsuladapter: debug

nacos-consul-adapter:
  mode: direct
